name: Dependabot auto-release

on:
  schedule:
    - cron: '09 5 1 * *' # At 05:XX on day-of-month 1 (UTC)
    # Just for testing purposes - run every 5 minutes
    # - cron: '*/5 * * * *' # Every 5 minutes

permissions:
  contents: read
  pull-requests: write

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/dependabot-auto-release@main
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
